import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@/styles/css/style.css";
import "@/styles/css/bootstrap.css";
import "@/styles/css/responsive.css";
import "@/styles/css/nprogress.css";

// import Header from '@/components/header/header'

const inter = Inter({ subsets: ['latin'] })

// this is like the main parent of component - it will wrap all of the page
//it is like <layout></layout>
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
         {/* <Header></Header> */}
        {children}
        </body>
    </html>
  )
}
