export const contextType = {
	SHOW_MOBILE_MENU: "SHOW_MOBILE_MENU",
	WINDOW_SIZE: "WINDOW_SIZE",
	SHOW_POP_UP_SEARCH: "SHOW_POP_UP_SEARCH",
	MENU_OPTION_DROP_DOWN: "MENU_OPTION_DROP_DOWN",
	SET_HEADER_STYLE: "SET_HEADER_STYLE",
	IS_ADMIN_PANEL: "IS_ADMIN_PANEL",
	IS_LOADING: "IS_LOADING",
	IS_NOT_AUTHENTICATED_USER: "IS_NOT_AUTHENTICATED_USER",
	IS_REGISTRATION_SUCCESSFUL: "IS_REGISTRATION_SUCCESSFUL",
};
